services:
  cups:
    container_name: cups
    image: curiouscocoon/docker-cups-pdf-airprint:latest
    environment:
      - CUPSADMIN=CHANGE_ME
      - CUPSPASSWORD=CHANGE_ME
    volumes:
      - ./cupsdocker/services:/services
      - ./cupsdocker/config:/config
    network_mode: host
    restart: unless-stopped